### ISSUE TITLE
[Analytics: News] Analytics Development Readiness: Part I: Launch + Analytics setup

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#103]
Naming conventions:
- "Adobe Launch" and "Adobe Tags" refer to the same Adobe solution, the tag manager. This ticket will use the name "Adobe Launch", as it is being used in the SAP documentation

Goals:
- Dedicated Adobe Launch config for AEM EDS exists (to coordinate with Analytics team, via Adobe's Sankalp Singh)
- Dedicated Analytics Report(s) for AEM EDS exist (to coordinate with Analytics team, via Adobe's Sankalp Singh)
- No interference with other existing Launch instances / Analytics reports

Expected result:
- AEM EDS loads Launch library for "AEM EDS News" (configured to load the Adobe Analytics extension)
  - Load launch library and extensions
  - Run SAP Page Footer Script
- EDS News developers can access Analytics Report(s) (e.g., page view)
- EDS News developers can disable Launch library loading by URL parameter

References:
- SAP EDDL documentation: https://wiki.one.int.sap/wiki/display/DBA/EDDL+v.1.0.0.0+RC
- SAP instructions and best practices on how to load the Adobe Launch library: https://wiki.one.int.sap/wiki/display/DBA/EDDL+v.1.0.0.0+RC > Global Launch Code
- SAP Page Footer Script: https://wiki.one.int.sap/wiki/display/DBA/EDDL+v.1.0.0.0+RC > Footer Code

**Comment by benpeter** [comment]
currently blocked on input, see https://adobe-dx-support.slack.com/archives/C05JM4HS24E/p1707908114785749?thread_ts=1707836773.289899&cid=C05JM4HS24E

**Comment by pahupe** [comment]
Sankalp Singh has provided an initial Launch and Analytics configuration for Content Hub Zone "News" for development here:

SAP News EDS [EDDL][AA]
- Launch Header Development: https://assets.adobedtm.com/ccc66c06b30b/6fa889b263e0/launch-3318725e3375-development.min.js
- Launch Header Staging: https://assets.adobedtm.com/ccc66c06b30b/6fa889b263e0/launch-6615f1bb001d-staging.min.js
- Launch Footer script: type="text/javascript">_satellite.pageBottom();

Ref: https://adobe-dx-support.slack.com/archives/C05JM4HS24E/p1710163753745349

**Comment by pahupe** [comment]
Three report Suites have been created (tracking DEV and QA). They can be accessed via https://experience.adobe.com/#/@sap/so:sap0/analytics/spa/#/workspace
- SAP on AEM EDS (QA and DEV): https://experience.adobe.com/#/@sap/so:sap0/analytics/spa/#/workspace/edit/66029e569e18e82d8c701761
- SAP News EDS : Site Performance Dashboard: https://experience.adobe.com/#/@sap/so:sap0/analytics/spa/#/workspace/edit/660d39bfd1fb454d216ddf56 > dialog: click "continue anyways"
- AEM News EDDL - Validation: https://experience.adobe.com/#/@sap/so:sap0/analytics/spa/#/workspace/edit/660d3c66d1fb454d216ddf7a > dialog: click "continue anyways"

For Adobe staff, access is managed by Sankalp Singh. SAP employees have to fill out a form: https://workzone.one.int.sap/site#workzone-home&/groups/7UUKUGSfGsr9GYoBGH5RZo/overview_page/Hd8VJpy5j1mScZiMFk4GAk

**Comment by pahupe** [comment]
Done.
