### ISSUE TITLE
panel block

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#108]
https://news.sap.com/2023/02/international-womens-day-2023-empathy-is-our-superpower-to-embrace-equity/

Old:
![image](https://github.com/urfuwo/hlx-test/assets/398734/0cf8eee0-63b2-4398-905c-29291ec5f25d)

New:

![Image](https://github.com/urfuwo/hlx-test/assets/2643450/51af7f05-103e-4010-ac6d-55a41f90c000)

Figma: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=2092-100341&mode=design&t=oGjZrklt5hCErBMt-4
discussion: https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1707347006655619

- [x] Import
- [ ] Block implementation

**Comment by larsauffarth** [comment]
@mhaack How can we identify if it is a promo block with the rules we have already in place or if it is a panel block? the outer html looks similar on /news/0000/the-article

**Comment by mhaack** [comment]
> the outer html looks similar on /news/0000/the-article

Yes and this is what it should. This version is no exact 1:1 copy it is ok to be re-styles. I think in /news/0000/the-article lets get some styles on the two register buttons and the rest is fine:
![Screenshot 2024-02-26 at 12 17 44](https://github.com/urfuwo/hlx-test/assets/2643450/c1f54459-a85b-4bcb-8fad-6be41e081d6c)
