### ISSUE TITLE
in-page table of contents

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#111]
Side nav is optional. Some long-form content will need it, some will not. So the content owner/author will need the ability to add side nav, if they need it—and the body of the page will start at column 3. If not used, start at column 1.

Content Hubs Figma: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=891-41409&mode=design&t=FWpXdKc0ZJ2AyKzd-4

<img width="156" alt="Screenshot 2024-02-15 at 17 20 28" src="https://github.com/urfuwo/hlx-test/assets/41549648/e11ff422-c519-422c-9efd-64a96b3925ad">

Brand Design: https://www.figma.com/file/OFEfvhyXJvYJ6MQZ30699m/v2.0-Brand-Digital-Design-System?type=design&node-id=7625-32246&mode=design&t=K62uHnxv6G3K65XD-0

**Comment by benpeter** [comment]
whoever does this be sure to talk to @mhaack before going ahead, he has plenty of references

**Comment by mhaack** [comment]
Samples from other projects:
* https://github.com/hlxsites/sunstar-foundation/tree/main/blocks/toc
* https://github.com/hlxsites/nokia/tree/main/blocks/toc

**Comment by saurabh-khare** [comment]
@benpeter @mhaack Should this not be part of cupcake? Especially when a big whitespace looms on the left in 3 column layout. I can start working on it since we now fixed the L3 layout.

**Comment by larsauffarth** [comment]
As @saurabh-khare  started on the L2 Grid, I'll take this one

**Comment by larsauffarth** [comment]
In this first iteration, shall we add dynamic highlighting of the currently viewed section? (in the screenshot the currently active one is highlighted in blue) or would that be static?
