### ISSUE TITLE
L3 grid system

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#116]
Goals:
* Implement a 12-column based grid system with fixed margins (left/right), fixed gutter space (space between columns) where the elements (e.g. cards) that span 1..n columns stretch
* For 1600px+ width, implement a grid system where the margins enlarge, but neither the columns nor gutter resize

Basically, this creates a grid as on the existing pages (https://news.sap.com/tags/ai/) with "stretching" elements

References: 
* https://sap.frontify.com/document/223141#/layout/grid-breakpoints
* https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1707727508931139

**Comment by benpeter** [comment]
@saurabh-khare -- please focus on L3 for now, other levels later + split to separate issues (happy for you to create these)
