### ISSUE TITLE
Implement related solutions block for article pages

### ISSUE THREAD

**Issue by mhaack** [urfuwo/hlx-test#120]
See [Figma](https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=891-41401&mode=design&t=3FBBy6sZRrnPwp4Q-4)

![Screenshot 2024-02-12 at 10 45 20](https://github.com/urfuwo/hlx-test/assets/2643450/3f6e6cab-7f15-4adf-a4c9-fb488282b354)

**Comment by benpeter** [comment]
```
+--------------------------------------------------------------------------+
| Resource Cards                                                           |
+--------------------------------------------------------------------------+
| title | slugline | Lorem.... | Link | <img>  | hasbluebaronslug?         |
+--------------------------------------------------------------------------+
| title | slugline | Lorem.... | Link | <img>  | hasbluebaronslug?         |
+--------------------------------------------------------------------------+
| title | slugline | Lorem.... | Link | <img>  | hasbluebaronslug?         |
+--------------------------------------------------------------------------+
```
does that ☝️  make sense for the authoring experience?
the headline would be a heading and not part of this, right?
thinking of the following structure:
```
resource-list/
	resource-list.js
	resource-list.css
	resource-card/
		resource-card.js
		resource-card.css
```

so the card as such can be held reusable.
am I making sense?

**Comment by benpeter** [comment]
the other approach I could think of is that each card is just a cell and the we have a convention on which markup to use

**Comment by sdmcraft** [comment]
I'd have a slight inclination towards the 2nd approach though I don't' have a strong opinion on this.  Basically just have a variant of the plain cards block like `Resource Cards` as it simple and has similar semantics as usual `cards` . I think your main reason for the first option is its ease of expressing different items within the card like title etc. while in the second case, its done by convention. For that, since we have block library setup, it should be easy enough for the authors to just copy over the block and adapt the content in it.

**Comment by mhaack** [comment]
I think option two is more natural for the author. But why invent an new block content structure? Why not go with the cards block content structure, see https://main--aem-block-collection--adobe.hlx.live/block-collection/cards.md

On the code org I think we can have this simpler and flat structure:

```
/cards
   cards.js
   cards.css
/product-cards
   ...
/artictle-cards
  ...
```
Where product cards, article cards etc. share common code with cards.
An alternative approach would be once cards block for everything, like done here https://github.com/hlxsites/danaher-ls-aem/tree/main/blocks/card-list (ignore the name, that should be `cards` only).

**Comment by benpeter** [comment]
thanks @mhaack -- much appreciated. will follow that guidance :)
