### ISSUE TITLE
Font Family Configuration Lacking Fallbacks

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#136]
it appears that we're exclusively using the "72 Brand" font family without defined fallbacks. Specifically, our font-family is set to "72 Brand" as seen in the `fonts.css` file:

```css
font-family: "72 Brand";
```
[Font CSS Reference](https://github.com/urfuwo/hlx-test/blob/6b995787e86eb9562162b2f788ced9a1ed66aa15/styles/fonts.css#L3)

However, there's an inconsistency in our hero component, where the `--sapFontFamily` variable includes "72" among its values, alongside "72full", Arial, Helvetica, and sans-serif as fallbacks:

```css
--sapFontFamily: "72", "72full", Arial, Helvetica, sans-serif;
```
[CSS Variables Reference](https://github.com/urfuwo/hlx-test/blob/6b995787e86eb9562162b2f788ced9a1ed66aa15/themes/sap_glow/css_variables.css#L806)

This discrepancy might lead to display issues across different environments where "72 Brand" or "72" fonts are not available, particularly since there seems to be no fallback for the primary "72 Brand" font setting in `fonts.css`.

see also https://github.com/urfuwo/hlx-test/pull/134#issuecomment-1948414124

**Comment by sdmcraft** [comment]
This is done via https://github.com/urfuwo/hlx-test/commit/70e0999750a78018db2e8f6ecc092764871cd34e
