### ISSUE TITLE
L2 Author Profile Card

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#148]
Approach:
- editor enters link to author page
- card is filled from index data based on author link

```
+------------------------------------
| Author Profiles
+------------------------------------
| https://x-y-z/topics/author/aaron 
| https://x-y-z/topics/author/brian
| https://x-y-z/topics/author/candice
+------------------------------------
```

![Image](https://github.com/urfuwo/hlx-test/assets/398734/ab609f48-46b4-4245-b77b-960144f2208e)

References:
* L2, list of author profiles: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65445&mode=design&t=LaI6dbu2dNrDhXN1-4

**Comment by pahupe** [comment]
Changed block name in example to "Author Profiles" to match the block on the L2 blog/ page
