### ISSUE TITLE
content list, filter defined by author

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#149]
sample reference https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-66546&mode=design&t=VWyIlxICkvP13Nl3-4

Author can define articles shown by the dimensions of
- tag
- author
- topic
- content type
- path
- limit (number of cards)

Change: Sorting by recency: This will be covered separately in #211

"Read more" button is a manually created button, not part of this block.

styling of variations handled in https://github.com/users/urfuwo/projects/1/views/1?pane=issue&itemId=53851596

**Comment by larsauffarth** [comment]
Do we have a sample page yet where this component is present?

**Comment by benpeter** [comment]
> Do we have a sample page yet where this component is present?

we don't no.

**Comment by benpeter** [comment]
From an authoring perspective, this could be like

```
                                                          
 ┌───────────────────────────────────────────────────────┐
 │ Content List (variation)                              │
 ├─────────────────┬─────────────────────────────────────┤
 │ Tags            │ Security                            │
 ├─────────────────┼─────────────────────────────────────┤
 │ Authors         │ Thomas Saueressig                   │
 ├─────────────────┼─────────────────────────────────────┤
 │ Topics          │ Technology                          │
 ├─────────────────┼─────────────────────────────────────┤
 │ Content Types   │ Newsbyte                            │
 ├─────────────────┼─────────────────────────────────────┤
 │ Paths           │ /news/*                             │
 ├─────────────────┼─────────────────────────────────────┤
 │ Limit           │ 6                                   │
 └─────────────────┴─────────────────────────────────────┘
                                                          
```

**Comment by benpeter** [comment]
this can then tie in with https://github.com/urfuwo/hlx-test/blob/ds-website/blocks/article-list/article-list.js#L79

**Comment by larsauffarth** [comment]
Is it fair to assume that all relevant content items are listed in **articles-index.xlsx** https://sap.sharepoint.com/:x:/r/sites/207899/_layouts/15/Doc.aspx?sourcedoc=%7B780F2603-C711-4D9A-9E80-0A1E78DBE3F5%7D&file=articles-index.xlsx&action=default&mobileredirect=true ?

**Comment by benpeter** [comment]
> Is it fair to assume that all relevant content items are listed in **articles-index.xlsx** https://sap.sharepoint.com/:x:/r/sites/207899/_layouts/15/Doc.aspx?sourcedoc=%7B780F2603-C711-4D9A-9E80-0A1E78DBE3F5%7D&file=articles-index.xlsx&action=default&mobileredirect=true ?

if not, we'll have to adjust the index, but the assumption is correct, yes

**Comment by pahupe** [comment]
I have extracted the sorting requirement into a separate ticket #211
