### ISSUE TITLE
Content List refactoring & Content List additional styling

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#150]
Content List (https://github.com/users/urfuwo/projects/1/views/1?pane=issue&itemId=53850703) has another variation where cards are rendered without image.
**Variation 1** (Without images)
![Image](https://github.com/urfuwo/hlx-test/assets/398734/8d216883-d3ab-4b5c-9aeb-9dcd591871eb)

**Variation 2** (With images)
![Image](https://github.com/urfuwo/hlx-test/assets/398734/1bc0c6f0-48c1-42d7-b982-e13cb5d0d4a5)

To accomodate the changes it is required to refactor the Content List to allow independent styling of Content List and Related articles since as of now both the blocks depend on Article List to pull the data and apply the styles. This ticket is to render Content List such that:

1. Content list and Related articles are the blocks while article list becomes the helper
2. Content list and related articles should load their own styles so they can coexist on the same page. This means article-list.css will go away
3. Data manipulation (fetching, filter, sorting, pagination) will be part of the block itself
4. Helper class will load the card (with & w/o image) which will be used by the blocks themselves
5. Newly imported content will use Content List as a block not Article List, this means Article List will be removed as a block.

**Comment by benpeter** [comment]
another variation is #25 https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1353-79869&mode=design&t=e8kYOyuUXoneYvdD-0

also renaming this to "Content List" which is its name in Figma

**Comment by larsauffarth** [comment]
Seems to be blocked by #149

**Comment by saurabh-khare** [comment]
@benpeter @mhaack I see `blocks/article-list/article-list.js` and it has no `decorate` function, rather it has a utility function that is imported in `blocks/content-list/content-list.js` which is now actually the block. It is confusing to see one block loading functions of another block.  IMHO if article-list is no more a block we should not keep it under /blocks. WDYT?

**Comment by benpeter** [comment]
it is a block @saurabh-khare, just it's being used by other blocks as well, which is why I gave the exported function a more speaking name than just decorate

**Comment by saurabh-khare** [comment]
@benpeter So we say going forward we will continue to have article list as well as content list? Which will be used when? As per this ticket we style only the content list ?

**Comment by benpeter** [comment]
@saurabh-khare - I agree there is overlap, yes.
> As per this ticket we style only the content list ?
for the sake of this ticket yes: correct and let's look at the overlap separately and if/how we resolve this.

**Comment by saurabh-khare** [comment]
@benpeter After discussion with @mhaack we find that it is not possible to only style content list in its current form as changing its styles will require change in article-list.css which is loaded by related-articles block and impact its style as well. To summarise:
1. Content list and Related articles are the blocks while article list is a helper
2. Content list and related articles should load their own styles so they can coexist on the same page. This means article-list.css will go away
3. Data manipulation (fetching, filter, sorting, pagination) will be part of the block itself
4. Helper class will load the card (with & w/o image) which will be used by the blocks themselves
5. Newly imported content will use Content List as a block not Article List, this means Article List will be removed as a block.

@mhaack Please add/correct anything I missed.

**Comment by benpeter** [comment]
thank you @saurabh-khare - I'm good with that. will you take it on as part of this ticket?

**Comment by saurabh-khare** [comment]
@benpeter Yes. Do you want me to update its description ?

**Comment by benpeter** [comment]
> Do you want me to update its description ?
@saurabh-khare - yes please, and thank you. makes sense to consolidate that in the description
