### ISSUE TITLE
Link Tiles Group

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#151]
Editorially managed 

https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=3454-105400&mode=design&t=glKXo7mfv14np2pL-4

Block:
Icon + Link in each row

![Image](https://github.com/urfuwo/hlx-test/assets/398734/2c320f98-9609-42af-bf6d-502c48bca383)

Potential Variation:

![Image](https://github.com/urfuwo/hlx-test/assets/398734/20478ffa-fa75-44d8-be12-bb28d6d21211)

**Comment by mhaack** [comment]
We already have this block
