### ISSUE TITLE
section styles

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#153]
Goal: visual dividers should be implemented as borders on sections (defaulting to top)
background styling in section metadata (variants to be determined from Figma / with Dani and Elaine).

For this, use section metadata, as can be found in /news/0000/the-article-new.docx

figma samples for background styling
- https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65943&mode=design&t=evGziGhVZ935Alot-4
- https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65509&mode=design&t=evGziGhVZ935Alot-4
- https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-66390&mode=design&t=evGziGhVZ935Alot-4

figma sample for dividers
https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-65931&mode=design&t=evGziGhVZ935Alot-4

![Image](https://github.com/urfuwo/hlx-test/assets/398734/397247ea-bd45-4908-9cd7-7cccf8090e49)

![Image](https://github.com/urfuwo/hlx-test/assets/398734/5e5edf88-b6a7-4674-a5cc-e132e183a333)

![Image](https://github.com/urfuwo/hlx-test/assets/398734/8bd5dff1-72dc-4769-b5fe-3bfd420414c6)

**Comment by saurabh-khare** [comment]
@benpeter Can you provide more details? Designs, specs etc.

**Comment by benpeter** [comment]
back to start until unblocked via #182
