### ISSUE TITLE
Hero - Flex Height

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#156]
Update: Changed name. "Hero - Flexible Height" is the official name.
Ref: https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1709831905227339?thread_ts=1709807073.301429&cid=C06H8UNQ3RS

Reqs (rephrased):
- Flexible Height: Hero fluidly adjusts to the amount of content in the hero
- Background: Choice of either pure color OR pattern (image) background (seems like it will be treated as "image" background). Example of "pattern background" https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1709813514476679?thread_ts=1709807073.301429&cid=C06H8UNQ3RS
- No buttons for now

==

https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-66162&mode=design&t=VWyIlxICkvP13Nl3-4

![Image](https://github.com/urfuwo/hlx-test/assets/398734/fb6244b3-9b54-4321-8261-7d1f0d8184fb)

also needs to be able to take a background image, see
https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=3797-101884&mode=design&t=YJDSOoj8I5PyddrZ-4

**Comment by pahupe** [comment]
Blocked, as #135 must be addressed first
