### ISSUE TITLE
adjust importer to create `Embed` blocks for YT videos

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#190]

**Comment by benpeter** [comment]
there are inline and standalone links to YT videos that are supposed to open in a modal, meaning we need explicit `embed` blocks for inline videos, see https://github.com/urfuwo/hlx-test/issues/173#issuecomment-1965425872

**Comment by mhaack** [comment]
This is already done. If the video has a placeholder today it gets transformed to an `embed` block otherwise just a link.

**Comment by mhaack** [comment]
See https://main--hlx-test--urfuwo.hlx.page/news/2023/11/sap-mercedes-amg-petronas-f1-team-join-forces-drive-efficiency and #173
