### ISSUE TITLE
L2 2nd-level navigation

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#196]
see (3) on  https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=3454-105120&mode=design&t=ST1BLK8gnuwT9oMC-4

**Comment by saurabh-khare** [comment]
@benpeter Can you specify what is required in this ticket? It is not clear from figma.

**Comment by benpeter** [comment]
I expect (3) to already comply with the side navigation work you did earlier and showed today @saurabh-khare 
On 28, I am unclear myself, looking at Figma I guess we'll probably need a call with Elaine next week to walk us through that.
I'll open a thread with her on Slack

![image](https://github.com/urfuwo/hlx-test/assets/398734/e71b9fad-4d28-46f6-a175-c47c442ef2ad)
