### ISSUE TITLE
Allow pagination for Content Lists

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#199]
Content Lists should allow pagination and then work like shown in Figma: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=1507-66028&mode=design&t=UHrpSbOtHwMtVMTm-4

![Image](https://github.com/urfuwo/hlx-test/assets/398734/de5386eb-9f3b-44e7-b5e6-45b019893ae1)

![Image](https://github.com/urfuwo/hlx-test/assets/398734/71929329-4434-4659-af69-d68b9ff50b0a)

see also #149 #150

**Comment by ok** [comment]
UDEx component available: https://pages.github.tools.sap/UDEx/digital-design-system/?path=/docs/components-navigation-pagination--docs&globals=theme:Horizon+Brand

**Comment by benpeter** [comment]
closing in favor of #308
