### ISSUE TITLE
Content Hub Masthead

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#2]
**Goal**: Implement the content hub header

The Master Header on the Content Hub implements Global navigation, allowing users to access different sections of Content Hub i.e. Blogs, News, Press Release and so on. 
It supports two level navigation where users can first land on the hub and based on the contents on the hub the second level navigation is populated. 
All the navigation links are manually contributed, where a Global content team contributes to the document (globalnav.docx/nav.docx) and every hub team contributes their own second level navigation. 
![image (1)](https://github.com/urfuwo/hlx-test/assets/41549648/638f461a-069b-4841-ae6c-8e7c2551f50b)
![image (2)](https://github.com/urfuwo/hlx-test/assets/41549648/10682255-b92a-45a0-8ba5-ee49f4a82508)
![image](https://github.com/urfuwo/hlx-test/assets/41549648/9e12f2da-0522-48f1-a036-dd4c1bd1914c)

Global navigation (top-level) features Explore section (different from Explore SAP) which opens a flyout menu where user can seek further information regarding content hub. 
Ref: https://news.sap.com/2023/12/being-human-in-the-age-of-ai/ > top line (SAP News Center)

NOTE: The header does **not** comprise the breadcrumb line "Corporate Blog"

**Design**: 
Old design: https://www.figma.com/file/OFEfvhyXJvYJ6MQZ30699m/v2.0-Brand-Digital-Design-System?type=design&node-id=2822%3A829&mode=design&t=2HIhIC3XND2WyiZb-1
New Content hub design: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=269-30889&mode=design&t=fud1mE0It37v2hWa-0

**Specifications**(Old): https://sap.frontify.com/document/223143#/-/masthead

**Header documentation:**
https://github.wdf.sap.corp/pages/designsystem/sap-simple-elements/?path=/docs/header-integration-guide--get-started

**Test Explore SAP menu JSON URL**
https://contextualnavigation.api.community-qa.sap.com/navigation_explore_sap/explore_sap/de/data_latest.json

**Assumptions**: 
As of now implementation of Explore SAP is out of scope and lies with the development of master header UI5 web component

**Comment by benpeter** [comment]
@saurabh-khare good to close?

**Comment by saurabh-khare** [comment]
> @saurabh-khare good to close?

Yes this can be closed.
