### ISSUE TITLE
Validate usage of Design Tokens

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#20]
Observations: 
* Design Tokens (SAP CSS Variables) have been used to setup the hlx-text site. Some variables were chosen without proper validation by SAP and need to be validated / corrected by SAP experts
* Currently, the Design Tokens are loaded multiple times (see https://github.com/urfuwo/hlx-test/issues/19). The design tokens values differ, so text supposed to show in white (--sapButton_Information_Active_TextColor) actually shows in blue, see Banner elements (https://main--hlx-test--urfuwo.hlx.page/blog/2023/12/being-human-in-the-age-of-ai)

Goals:
* SAP to pick/indicate the correct design tokens
* Correct the CSS templates accordingly

**Comment by pahupe** [comment]
Marked as "blocked", as this is a clean-up task to be done after we have implemented a lot of blocks

**Comment by benpeter** [comment]
closing for now, we can re-visit later
