### ISSUE TITLE
content list iteration 2: sorting

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#211]
Split-off from #149 

Context: Sorting requires stream-sorting in the underlying ffetch library, hence this has been extracted from #149. Details: (Meaningful) sorting and then result set limiting can only be implemented at the ffetch library level

Goal: Implement sorting by recency

**Comment by benpeter** [comment]
@pahupe -- I think the index will always be sorted by recency, because pages are appended on publication, so you just need to reverse the result IIUC
@mhaack CMIIW

**Comment by pahupe** [comment]
Update: the data will not be filtered in JavaScript, but we will use Excel's sorting functionality to presort the data by publication date (right now the only sorting criterion)

**Comment by pahupe** [comment]
@mhaack : Can you please validate that this how we should implement the sorting in Excel:

Before we start: I created a custom copy of the /articles-index.xlsx here: /draft/hupe/test-articles-index.xlsx (https://sap.sharepoint.com/:x:/r/sites/207899/Shared%20Documents/website/draft/hupe/test-articles-index.xlsx?d=wfd50d6ebabed443799f4a8781b74a623&csf=1&web=1&e=KA8OgY) to not break the existing index. 

Steps:
* I updated the publication date of an article (/blog/2024/01/fusing-sustainability-and-ai-for-global-progress) to Feb 20 to make it move up in the article list to position 2
* I noticed that the publicationDate is updated in raw_index, but no automatic re-sorting in Excel is applied (despite the fact that I marked the column as the "sort column"). So, the article does not move up in the list in raw_index.
* Hence, I created a derived index "helix-default" in a separate sheet, added all headers to row 1 and the sorted data formula to cell A2 using formula (sort by column publicationDate column, which is column 10): =SORT(Table1, 10, -1) 
* I published the XLS and can see that in the resulting index (https://main--hlx-test--urfuwo.hlx.page/draft/hupe/test-articles-index.json) the article shows up at expected position 2

Open points:
* All empty value cells now have a numeric value 0 in the derived index, but that is not a blocker

NOTE: I followed the example given here: https://www.aem.live/developer/indexing#enforcing-noindex-configuration-with-custom-index-definitions for helix-default

@mhaack : Please validate and I'll apply the same to /articles-index.xlsx

cc @benpeter, @sdmcraft, @saurabh-khare

**Comment by benpeter** [comment]
as discussed ok to use as above @pahupe

**Comment by mhaack** [comment]
> All empty value cells now have a numeric value 0 in the derived index, but that is not a blocker

This is Excel default behaviour.

**Comment by pahupe** [comment]
Done:
* /articles-index.xlsx now contains a derived index "helix-default" that sorts by publicationDate (desc).
* Page https://main--hlx-test--urfuwo.hlx.page/draft/hupe/test-content-lists > first list shows the articles in correct order.
