### ISSUE TITLE
Add date option for cards

### ISSUE THREAD

**Issue by mhaack** [urfuwo/hlx-test#222]
This extends and applies to #146 #142 

The cards block should get an option to show the publish date of an referenced doc/article. See https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=3795-94193&mode=design&t=S8BYoiVyguDUyFRO-4

**Comment by pahupe** [comment]
Use the metadata field article:published_time as the date
Use as textual prefix "Updated on "
Validate with Glenn and Colleen

**Comment by sanmishr** [comment]
@mhaack @benpeter  clarification required - 

https://main--hlx-test--urfuwo.hlx.page/blog/2023/05/sap-a-leader-2023-gartner-magic-quadrant-wms on this page I can see publish date 


![Image](https://github.com/urfuwo/hlx-test/assets/41055186/6151ff45-970a-4973-9bad-c14ba0cd8dff)

https://150-content-list-refactoring--hlx-test--urfuwo.hlx.page/draft/skhare/content-list-test



![Image](https://github.com/urfuwo/hlx-test/assets/41055186/8c71f551-437c-4239-885e-a74be9ff9721)

**Comment by benpeter** [comment]
maybe @saurabh-khare has already done this on the go. have you?

**Comment by saurabh-khare** [comment]
@benpeter Yes this has been already implemented

**Comment by benpeter** [comment]
thanks @saurabh-khare  - moved to done
