### ISSUE TITLE
Promo Banner styling for newsletter

### ISSUE THREAD

**Issue by mhaack** [urfuwo/hlx-test#238]
The `Promo (Newsletter)` variant of the block requieres extra styling like always blue background, button alignment etc.

Figma:
https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=4011-150177&mode=design&t=jNTCdfDJB6HbooYn-4

Examples:
https://web1.udex.services.sap.com/blog/2022/08/sap-successfactors-innovation-tackle-2022-hr-trends

This can be implemented together with #237

**Comment by sanmishr** [comment]
done
