### ISSUE TITLE
Non-curated L2 Topic and Tag Pages

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#251]
Figma doesn't currently include an example of a non-curated Topic Page.
An example would be https://main--hlx-test--urfuwo.hlx.page/topics/ai which is currently off in terms of styling.

Tasks:
1. create a template that is a reasonable representation for non-curated Topic Pages (authoring team can later change the template, just needs to look OK)

2. create shared side navigation for 2 sample topic groups and map that side navigation through the metadata sheet
- use topic group sustainbability, sub topics of green software development, carbon accounting for an example 
- all other topics don't use a side navigation (meaning L2 needs to work without a side nav)

**Comment by pahupe** [comment]
Related to #250

**Comment by pahupe** [comment]
Will be done in one go with #250

**Comment by pahupe** [comment]
Requires the #250 PR (https://github.com/urfuwo/hlx-test/pull/258) to be merged, as the code changes are in #250

**Comment by pahupe** [comment]
Replaced with #250 and PR https://github.com/urfuwo/hlx-test/pull/258
