### ISSUE TITLE
LinkedIn Video links should open in new tab

### ISSUE THREAD

**Issue by mhaack** [urfuwo/hlx-test#254]
Today LinkedIn video's are not embed and just open in a new video. Add `target=blank` to LinkedIn video links and make sure they are not embed.

Sample Page: https://web1.udex.services.sap.com/blog/2023/11/generative-ai-business-platform-systems-of-intelligence

**Comment by mlangfordsap** [comment]
This is another contradiction to the previous guidance, but easy enough to implement within the embed block implementation I guess.  See: https://github.com/urfuwo/hlx-test/pull/252

Probably best to decline that PR then, as that work implements LinkedIn as an embed with consent overlay and I'll go ahead and update it so no LinkedIn embeds are used, no consent overlay is presented on LinkedIn placeholders, and instead the placeholders link out to the LinkedIn link instead.

**Comment by mhaack** [comment]
Guidance from Angie & Colleen is to have LinkedIn Video (and maybe all LinkedIn links) go to new video. Hence in the content they are just images with links. No need for an embed for block for this use case.
