### ISSUE TITLE
Stand alone link and button styling

### ISSUE THREAD

**Issue by rootpea** [urfuwo/hlx-test#268]
Links and button outside a block should be styled accordingly:

Link
**Primary button**
_Secondary button_

Should also apply to other blocks where no explicit button styling is set, e.g. cards, columns

**Comment by benpeter** [comment]
there are no stand-alone buttons per design system governance

**Comment by rootpea** [comment]
@benpeter 

<img width="854" alt="Screenshot 2024-03-12 at 14 24 22" src="https://github.com/urfuwo/hlx-test/assets/52969899/a1592dd2-1223-4979-9d31-1f40dd3ebe15">

**Comment by rootpea** [comment]
<img width="878" alt="Screenshot 2024-03-12 at 14 25 13" src="https://github.com/urfuwo/hlx-test/assets/52969899/75aa1ec0-4516-4735-93d0-465064339d51">

**Comment by benpeter** [comment]
ah, interesting, thanks -- that's different from what the design team said :)

**Comment by sanmishr** [comment]
assigning this to me as I will be free from my issues by the end of the day .

**Comment by sanmishr** [comment]
@mhaack  do we still need this ticket ?  I think independent buttons are now working .


![Image](https://github.com/urfuwo/hlx-test/assets/41055186/9afd28bc-c247-4cba-a599-1a75848add8c)

or am I missing something ?

**Comment by mhaack** [comment]
As this discussed the last of the three samples about should be a link with > and different blue color
