### ISSUE TITLE
Limit article list length

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#334]
Task was split off from https://github.com/urfuwo/hlx-test/issues/279

Motivation: Article lists (which are e.g. being used on dynamically generated author, topic and tag pages like https://main--hlx-test--urfuwo.hlx.page/topics/sustainability don't have an article list limit. They take very long to load and require editors to scroll endlessly.

Full scope task: according to Figma specs (#tbd)
- if the total number is < 10, we should show all entries
- if the total number is between 11 and 20, we should show 10 and a "Show more" button (see similar logic built into content lists)
- if the total number is more than 20, we should introduce pagination
This should be done in for article lists and content-lists to not build the logic twice

Reduced scope task (intermediate solution):
- Limit the list to max 24 entries. This creates full rows for rows of 2, rows of 3 and rows of 4

**Comment by pahupe** [comment]
For March 22, the intermedia solution would be an achievable target.

**Comment by sanmishr** [comment]
closing this ticket as per discussion with @pahupe  as content task is not required inside github. Functionality is part of #308
