### ISSUE TITLE
Implement "Table" block

### ISSUE THREAD

**Issue by mhaack** [urfuwo/hlx-test#336]
Implement a table block, based on boilerplate https://www.aem.live/developer/block-collection/table which is used on several pages from Insights.

Example:
* https://www.sap.com/insights/viewpoints/the-c-suite-gets-an-ai-upgrade.html
* https://main--hlx-test--urfuwo.hlx.page/blog/the-c-suite-gets-an-ai-upgrade

- [x] Import
- [x] Add table block
- [ ] Final styling

**Comment by benpeter** [comment]
@mhaack - should we leave this open?

**Comment by mhaack** [comment]
Yes for the main styling. We only have a very basic styling and the final styles are missing as they have not been specified.
