### ISSUE TITLE
"Promo Tile" element

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#38]
Context:
* The element "Promo Tile" (design ref 23, see below) shall only be embedded in a template at the bottom of the page
* NOTE: A very similar/same element exists that will be embedded in the body / copy of blog pages (design ref 16), but its design is not yet ready (WIP)
* UPDATE: There no longer is an "align left" variant
 
Goals: 
* Rename the AEM EDS block "cta-banner" to "promo tile"
* Style it according to the design ref Nr. 23 (see references below)
* Add an instance to the footer, as all promo tiles shall reside in the footer of the page

Non-goals:
* For the element to be included in the blog body, there will be a separate GH issue

References:
* Slack discussion: https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1707207502775329
* Design references Nr. 23 (promo tile in the footer of the page) and Nr. 16 (WIP block in article body): https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=652-8749&mode=design&t=HeGsZWUTcfDNTQ1v-0

**Comment by benpeter** [comment]
duplicates #130
