### ISSUE TITLE
Implement "Article Collection" block for L3 sidebar

### ISSUE THREAD

**Issue by mhaack** [urfuwo/hlx-test#389]
Implement "Article Collection" block to be used in the right sidebar to link to other related articles as a manually curated list of links. The author must provide all the details, no lookup etc. will be needed. Each table row can have:

* link to internal or external page
* optional eyebow text above the link
* optional details below the link

See: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=4654-139510&mode=design&t=VojBIR29IkDtz9Gy-4

**Comment by saurabh-khare** [comment]
@eduardseifert Are you working on this ticket?

**Comment by eduardseifert** [comment]
@saurabh-khare I unassigned from this one and will focus on the Main Navigation for the Design Portal.
