### ISSUE TITLE
Avatars in cards - alignment

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#412]
Elaine Shih reviewed the avatars in cards, and provided feedback:

_The spacing is a little bit off, as the bottom margin of the card should be 24, so I think it needs to bump up and down a tiny bit._

![Group 164029](https://github.com/urfuwo/hlx-test/assets/33486726/ddaaf18c-fcce-4609-a988-ff1e75811e89)

**Comment by saurabh-khare** [comment]
@eduardseifert Is there any update on this ticket?

**Comment by eduardseifert** [comment]
> @eduardseifert Is there any update on this ticket?

Created PR: https://github.com/urfuwo/hlx-test/pull/468
