### ISSUE TITLE
Implement "Profiles" block

### ISSUE THREAD

**Issue by saurabh-khare** [urfuwo/hlx-test#446]
Similar to author profiles block we need a profiles block which shows manually curated profiles instead of pulling information for authors. For every profile editors can add
1. Image
2. Name
3. Description

<img width="1204" alt="Screenshot 2024-04-05 at 18 06 53" src="https://github.com/urfuwo/hlx-test/assets/41549648/ab4d6ae8-2888-4ef2-8995-c2e0b302a491">

The approach must be to create a reusable element like an avatar or a picture card and use it across author profiles and generic profiles

**Comment by rjwtrmn** [comment]
I accidentally duplicated this and named branch etc. with other ticket number. Will close this one and use the other.
