### ISSUE TITLE
Generic redirect for blog articles

### ISSUE THREAD

**Issue by sdmcraft** [urfuwo/hlx-test#61]
On https://news.sap.com/ , all blog articles get redirected with /blog removed from path. For e.g https://news.sap.com/blog/2024/01/leylah-fernandez-new-sap-brand-ambassador/ -> https://news.sap.com/2024/01/leylah-fernandez-new-sap-brand-ambassador/

**Comment by benpeter** [comment]
this has not been fully clarified yet, let's discuss first.
current view is we'll have everything at /blog not / potentially including topics, videos, tags, and authors.

**Comment by benpeter** [comment]
ack. the domain will change as well, so we'll need to have redirects from old to new domain anyway and can handle along these lines; cc @urfuwo

**Comment by pahupe** [comment]
@benpeter : Redirects are managed ticket is here: https://github.com/urfuwo/hlx-test/issues/66

**Comment by sdmcraft** [comment]
Closing this since the redirects would be managed via #66
