### ISSUE TITLE
Article Card as a web component

### ISSUE THREAD

**Issue by benpeter** [urfuwo/hlx-test#68]
- prerequisite: Article Card available as a web component
- then use the article card in places where articles are now shown (https://github.com/urfuwo/hlx-test/blob/main/blocks/article-list/article-list.js#L15)

**Comment by benpeter** [comment]
blocked as we don't have a valid example of how to do the cards based on web components

**Comment by ok** [comment]
What about the ones that are [available here](https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=268%3A3637&mode=design&t=QTdKK8GJHTzw200x-1). can you access these?

<img width="1916" alt="Screenshot 2024-01-25 at 17 53 42" src="https://github.com/urfuwo/hlx-test/assets/54379826/58361f6d-07d4-43d6-a857-aafe26473c2b">

**Comment by benpeter** [comment]
looks good @ok - are these available as a UDEx web component?

**Comment by benpeter** [comment]
as confirmed on Slack by @ok 
- not available as UDEx component, so this remains blocked
- but the above design will be used in #69 to implement these cards as an EDS block
