### ISSUE TITLE
[Feedback to SAP] next page design iteration: missing design examples

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#72]
Context: SAP has provided a design example ("Concept A") for next-gen content hub blog pages here: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=269-30889&mode=design&t=RZkr5VBRC2kSmAUI-0. This design example is intended to be the foundation of the content hub / blog pages.

The example is fine, but unfortunately missing certain aspects, and therefore the design implementation in Adobe AEM EDS must make a lot of assumptions.

Please add illustrations for the following aspects to the example:
- There is no mobile breakpoint view
- It is not clear whether left-aligned cta-banner blocks are still supported (see https://news.sap.com/2024/01/is-supply-chain-innovation-possible-era-tighter-regulation/ as an example)
- No examples have been given for bullet lists (HTML: ul, ol)
- There is no example for the spacing of two consecutive paragraphs (without another element between them, e.g. image or cta-banner element)
- There is no example for pages whose first paragraph is an abstract (see https://news.sap.com/2024/01/is-supply-chain-innovation-possible-era-tighter-regulation/ as an example)
- No example for smaller headlines (h3, h4, h5, h6) is given

**Comment by pahupe** [comment]
@ok : I have two additional questions, which are not directly related to the page design, but more generic questions:

Q1: Links on the new design page (https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=269-30889&mode=design&t=RZkr5VBRC2kSmAUI-0) appear to be underlined even when not hovered, while the current design shows them as only underlined when hovered. Shall I use the link design (always underlined) from the new pages?

Q2: I could not find the "SAP Blue" color code (#008fd3) in the theme design tokens (sap_glow). Is there any design token matching that color? Or will this color code be discontinued?

**Comment by ok** [comment]
on Q1: no. I would be suprised if that would be the case. also easy to change afterwards
on Q2: it is a new design foundation. this should be the brand color variable: --sapBrandColor

**Comment by pahupe** [comment]
@ok : On Q1: the new design (https://sap.frontify.com/document/223142#/-/links) indicates that links shall now always be underlined (kudos to @saurabh-khare for spotting the reference)
On Q2: Ok, thanks. I will be using --sapBrandColor

**Comment by benpeter** [comment]
@pahupe is this still relevant or are we resolving these with Dani and Elaine on Slack on the go?
