### ISSUE TITLE
Styling of WebComponent HeroBanner

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#79]
Goal: The HeroBanner styling on article/blog pages matches the design given on https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=269-30889&mode=design&t=D0jJGSxZlJFSCg4b-0

Reference page (AEM EDS): https://main--hlx-test--urfuwo.hlx.live/blog/2023/12/being-human-in-the-age-of-ai

List of concerns:
* Text box padding and margin (spacing to the page border)
* Bounding box of the text (within the element)
* Technical integration of the background image (see EDS block hero.js code)

**Comment by benpeter** [comment]
@pahupe - just to be clear, this is a concern for the UDEx team, do I understand correctly?

**Comment by benpeter** [comment]
@pahupe - can you clarify this vs the other hero issues? It's unclear to me
