### ISSUE TITLE
Footer new design

### ISSUE THREAD

**Issue by pahupe** [urfuwo/hlx-test#95]
Goals: Implement the new footer design

NOTE: There are a few open pending questions (mismatches between our footer and the "standard" footer: https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1707236316695689

References:
* [Content Hub Footer] Figma design reference: https://www.figma.com/file/oSetT4LbatRmXlcB2A7V8Z/Content-Hubs-2024?type=design&node-id=891-41381&mode=design&t=w5ii1WkVdG1ceptO-4
* v2.0 Brand DS Footer https://www.figma.com/file/OFEfvhyXJvYJ6MQZ30699m/v2.0-Brand-Digital-Design-System?type=design&node-id=7582-50040&mode=design&t=ckoaPadscXdUGRKk-0
* [Default Footer] Frontify reference: https://sap.frontify.com/document/223143#/-/footer

**Comment by sdmcraft** [comment]
Need more clarity on what specific items we need to address here.

**Comment by sdmcraft** [comment]
Resolving this since the clarifications were received on [this thread](https://adobe-dx-support.slack.com/archives/C06H8UNQ3RS/p1707236316695689). Any followup items, if needed, can be taken up separately.
